[toolchain]
channel = "nightly-2025-03-20"
profile = "minimal"
components = ["clippy", "rustfmt"]
targets = [
    "aarch64-unknown-linux-musl",
    "armv7-unknown-linux-musleabihf",
    "loongarch64-unknown-linux-musl",
    "powerpc-unknown-linux-gnu",
    "powerpc64-unknown-linux-gnu",
    "s390x-unknown-linux-gnu",
]
